sudo: required

language: cpp
compiler: g++

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update -qq
    - sudo apt-get install -qq g++-4.8 qt5-qmake qtbase5-dev

script:
    - qmake -qt=qt5 -v -project
    - qmake -qt=qt5 Starlight.pro QMAKE_CXX=g++-4.8
    - make
